CODE_ROOT="$PWD"
# CUDA_VISIBLE_DEVICES=0,1 python train_multi_gpu.py \
#                         distributed.torch_distributed_debug=False \
#                         distributed.find_unused_parameters=True \
#                         distributed.init_method=tcp \
#                         distributed.world_size=2 \
#                         model.ratios=[8,5,4,2,2] \
#                         common.save_interval=1 \
#                         common.test_interval=1 \
#                         common.max_epoch=100 \
#                         common.log_interval=20 \
#                         common.amp=True \
#                         datasets.tensor_cut=120000 \
#                         datasets.batch_size=4 \
#                         datasets.num_workers=8 \
#                         datasets.fixed_length=1000 \
#                         datasets.train_csv_path=${CODE_ROOT}/datasets/libritts_100h.csv \
#                         datasets.test_csv_path=${CODE_ROOT}/datasets/libritts_test_all.csv \
#                         lr_scheduler.warmup_epoch=1 \
#                         optimization.lr=5e-5 \
#                         optimization.disc_lr=5e-5 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python train_multi_gpu.py \
                        distributed.torch_distributed_debug=False \
                        distributed.find_unused_parameters=True \
                        distributed.world_size=8 \
                        distributed.init_method=tcp \
                        model.ratios=[8,5,4,2,2] \
                        common.save_interval=2 \
                        common.test_interval=2 \
                        common.max_epoch=100 \
                        common.log_interval=1000 \
                        common.amp=True \
                        datasets.tensor_cut=120000 \
                        datasets.batch_size=4 \
                        datasets.num_workers=8 \
                        datasets.train_csv_path=${CODE_ROOT}/datasets/libritts960_train_all.csv \
                        datasets.test_csv_path=${CODE_ROOT}/datasets/libritts_test_all.csv \
                        lr_scheduler.warmup_epoch=1 \
                        optimization.lr=5e-5 \
                        optimization.disc_lr=5e-5 \
                        checkpoint.save_folder=/modelblob/users/v-zhikangniu/models/encodec640x_libritts960_multigpu \
                        hydra.run.dir=/modelblob/users/v-zhikangniu/models/encodec640x_libritts960_multigpu